FROM alpine:3.19

ENV NODE_VERSION 20.15.0

RUN addgroup -g 1000 node \
    && adduser -u 1000 -G node -s /bin/sh -D node \
    && apk add --no-cache \
        libstdc++ \
        tor \
    && apk add --no-cache --virtual .build-deps \
        curl \
    && curl -fsSLO --compressed "https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64-musl.tar.xz" \
    && tar -xJf "node-v$NODE_VERSION-linux-x64-musl.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && rm -f "node-v$NODE_VERSION-linux-x64-musl.tar.xz" \
    && apk del .build-deps

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Tor configuration
RUN mkdir /etc/tor
COPY torrc /etc/tor/torrc

FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80

CMD tor & nginx -g 'daemon off;'
